### ISSUE TITLE
Error when calling function with Survey Example in

### ISSUE THREAD

**Issue by 9LabsInc** [laanlabs/SwiftSurvey#1]
Hey!

First love this implementation and looking forward to getting it into my app, however I have hit an issue, sorry a bit of newb here…

I have a button calling a `@objc func`
```swift
@objc func startSurvey() {
    guard let questions = Bundle.main.path(forResource: "Questions", ofType: "json") else { print("Cannot get JSON"); return }
    let questionsUrl = URL(string: questions)
    guard let survey = try? Survey.LoadFromFile(url: questionsUrl!) else {return}
    let surveyView = SurveyView(survey: survey, delegate: self)
    let vc = UIHostingController(rootView: surveyView)
    self.present(vc, animated:true, completion: nil)
}
```

When I click the button I get this in the log

```
2022-08-19 16:25:23.487698+0100 AppTest[76515:7918780] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-08-19 16:25:23.487881+0100 AppTest[76515:7918780] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-08-19 16:25:23.490308+0100 AppTest[76515:7919147] NSURLConnection finished with error - code -1002
```
I enabled the App Transport plist trick but still having issues and I think it's finding the JSON as I am not getting the print output from my `guard`

Any help would be great, Thanks!

**Comment by cclaan** [comment]
My guess is the `URL(string:)` constructor is causing the issue. Try using the `URL(fileURLWithPath:)`
```swift
guard let questionsPath = Bundle.main.path(forResource: "Questions", ofType: "json"),
              let survey = try? Survey.LoadFromFile(url: URL(fileURLWithPath: questionsPath) ) else { return; }
        
```

**Comment by 9LabsInc** [comment]
@cclaan Thanks for the response but I now get `Type 'Survey' has no member 'LoadFromFile'` for this line
```swift
let survey = try? Survey.LoadFromFile(url: URL(fileURLWithPath: questionsPath) ) else { return; }
```

**Comment by cclaan** [comment]
That function is [here](https://github.com/laanlabs/SwiftSurvey/blob/ea9b14b37ff574a8897a7bc1a967562227aa9e9a/ios/SwiftSurvey/SurveyHelper.swift#L12)
Have you added the SurveyHelper.swift to your project?

**Comment by 9LabsInc** [comment]
@cclaan Ok no more errors which is awesome!! but when I click by button nothing appears, the button is in my RootViewController

```Swift
surveyBtn.addTarget(self,  action:#selector(startSurvey), for: .touchUpInside)

@objc func startSurvey() {
  print("Survey Button Clicked")
  guard let questionsPath = Bundle.main.path(forResource: "TravereQuestions", ofType: "json"),
			  let survey = try? Survey.LoadFromFile(url: URL(fileURLWithPath: questionsPath) ) else { return; }
  let surveyView = SurveyView(survey: survey, delegate: self)
  let vc = UIHostingController(rootView: surveyView)
  vc.overrideUserInterfaceStyle = .light
  vc.modalPresentationStyle = .formSheet //Added This line as app is for iPad only
  self.present(vc, animated:true, completion: nil)
}
```

Any ideas?

**Comment by cclaan** [comment]
Hm, i'd have to see more of the code.. does "Survey Button Clicked" get printed? did the guard / else fail ? try adding a print there

**Comment by 9LabsInc** [comment]
@cclaan Yes indeed the guard is failing

Does it have anything to do with the fact I had to add `SurveyViewDelegate` and these `func`
```Swift
	func surveyCompleted(with survey: Survey) {
		print("Survey Completed")
	}
	
	func surveyDeclined() {
		print("Survey Declined")
	}
	
	func surveyRemindMeLater() {
		print("Survey Later")
	}
```

**Comment by cclaan** [comment]
Might be an error like missing file, you can print it out:

```swift
let survey : Survey 
do {
   survey = try Survey.LoadFromFile(url: URL(fileURLWithPath: questionsPath) )
} catch {
   print("Could not load survey" , error)
}
```

**Comment by 9LabsInc** [comment]
@cclaan So sorry about this, it does produce an error
```
Could not load survey keyNotFound(CodingKeys(stringValue: "autoAdvanceOnChoice", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "questions", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "question", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"autoAdvanceOnChoice\", intValue: nil) (\"autoAdvanceOnChoice\").", underlyingError: nil))
```
This is my JSON File (Attached - Added TXT as GitHub not a fan of attached JSON files)
[questions.json.txt](https://github.com/laanlabs/SwiftSurvey/files/9384269/questions.json.txt)

**Comment by cclaan** [comment]
Loading the survey with that json works for me.. any chance you loaded a different file?   Were you able to run the sample survey ok?

**Comment by 9LabsInc** [comment]
@cclaan Definitely something wrong in my JSON I will debug that file thanks for your help
