### ISSUE TITLE
Required Field Validation

### ISSUE THREAD

**Issue by 9LabsInc** [laanlabs/SwiftSurvey#2]
Hi there, doing great with the library and got everything working except required field validation could you provide an example in the SurveyView that shows a how we could prevent a user from progressing if they've not answered a question, perhaps with a feedback message?

**Comment by cclaan** [comment]
Hi, sorry that is beyond the scope of what we built. As mentioned in README this was a quick project. It should be easy to modify to add that functionality if you want. And feel free to submit a PR with the addition. Otherwise I will put it on the list todo, but no guarantee we can get to implementing it.
Thanks

**Comment by 9LabsInc** [comment]
Fair enough and thank you for your reply.

In the meantime is it possible for you to tell me how to check if values have been selected or not in the `nextTapped()` function I have written `@State var` variable and a banner which I am happy to post if useful, but cannot work out how to check if there has been values selected or not?

Thanks for your efforts it is a really great little bit of code, super useful, I'd encourage making it a Pod for other people to use!

**Comment by cclaan** [comment]
The visibilityLogic code could be helpful if you want to write something generic like a validation step.
Otherwise you could do something hacky in nextTapped() 

```swift
        if let q = self.survey.questions[self.currentQuestion] as? MultipleChoiceQuestion {
            if !q.choices[0].selected {
                print("You need to select this!")
                return;
            }
            if let text = q.choices[2].customTextEntry {
                if Float(string: text) == nil {
                    print(" Invalid float")
                    return;
                }
            }
        }

```

**Comment by cclaan** [comment]
I threw a basic example for the case where a multiple choice question needs to be answered... I don't think it's quite your use, but you can probably modify

Branch:
https://github.com/laanlabs/SwiftSurvey/tree/validation_quick_idea

**Comment by 9LabsInc** [comment]
@cclaan Thank you so much, thats really kind of you
